-- ----------------------------
-- Table structure for "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"
-- ----------------------------
-- DROP TABLE "C##FHBOOT"."SYS_MANAGEMENTSYSTEM";
CREATE TABLE "C##FHBOOT"."SYS_MANAGEMENTSYSTEM" (
	"NAME" VARCHAR2(255 BYTE) NULL ,
	"PATH" VARCHAR2(255 BYTE) NULL ,
	"CLASSIFICATION" VARCHAR2(255 BYTE) NULL ,
	"SUFFIX" VARCHAR2(255 BYTE) NULL ,
	"ISDOWM" NUMBER(11) NULL ,
	"MANAGEMENTSYSTEM_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"."NAME" IS '文件名';
COMMENT ON COLUMN "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"."PATH" IS '文件路径';
COMMENT ON COLUMN "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"."CLASSIFICATION" IS '类型';
COMMENT ON COLUMN "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"."SUFFIX" IS '文件后缀';
COMMENT ON COLUMN "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"."ISDOWM" IS '是否可下载';
COMMENT ON COLUMN "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"."MANAGEMENTSYSTEM_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table SYS_MANAGEMENTSYSTEM
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"

-- ----------------------------

ALTER TABLE "C##FHBOOT"."SYS_MANAGEMENTSYSTEM" ADD CHECK ("MANAGEMENTSYSTEM_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHBOOT"."SYS_MANAGEMENTSYSTEM"
-- ----------------------------
ALTER TABLE "C##FHBOOT"."SYS_MANAGEMENTSYSTEM" ADD PRIMARY KEY ("MANAGEMENTSYSTEM_ID");
