
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SYS_MANAGEMENTSYSTEM`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_MANAGEMENTSYSTEM`;
CREATE TABLE `SYS_MANAGEMENTSYSTEM` (
 		`MANAGEMENTSYSTEM_ID` varchar(100) NOT NULL,
		`NAME` varchar(255) DEFAULT NULL COMMENT '文件名',
		`PATH` varchar(255) DEFAULT NULL COMMENT '文件路径',
		`CLASSIFICATION` varchar(255) DEFAULT NULL COMMENT '类型',
		`SUFFIX` varchar(255) DEFAULT NULL COMMENT '文件后缀',
		`ISDOWM` int(11) NOT NULL COMMENT '是否可下载',
  		PRIMARY KEY (`MANAGEMENTSYSTEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
